/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package posbackend;

/**
 *
 * @author Tylar
 */
public class ManagerPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private POSbackend posBackEnd;
    private int index=0;
    
    public ManagerPanel() {
        initComponents();
    }
    
    public void setMainFrame(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        posBackEnd = mainFrame.getPosBackEndMain();
        employeeNameLabel.setText(posBackEnd.getEmployeeNameBackEnd(index));
        timeSheetTextArea.setText(posBackEnd.getEmployeeClockBackEnd(index));
        netSalesField.setText(""+posBackEnd.getDailyTotal());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        clockInOutSpot = new javax.swing.JScrollPane();
        timeSheetTextArea = new javax.swing.JTextArea();
        previousEmployeeButton = new javax.swing.JButton();
        nextEmployeeButton = new javax.swing.JButton();
        netSalesLabel = new javax.swing.JLabel();
        netSalesField = new javax.swing.JTextField();
        employeeNameLabel = new javax.swing.JTextField();
        returnManagerButton = new javax.swing.JButton();

        jLabel1.setText("Name:");

        jLabel2.setText("Timesheet:");

        timeSheetTextArea.setColumns(20);
        timeSheetTextArea.setRows(5);
        clockInOutSpot.setViewportView(timeSheetTextArea);

        previousEmployeeButton.setText("Previous");
        previousEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousEmployeeButtonActionPerformed(evt);
            }
        });

        nextEmployeeButton.setText("Next");
        nextEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextEmployeeButtonActionPerformed(evt);
            }
        });

        netSalesLabel.setText("Net Sales:");

        netSalesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netSalesFieldActionPerformed(evt);
            }
        });

        employeeNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeNameLabelActionPerformed(evt);
            }
        });

        returnManagerButton.setText("Return");
        returnManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnManagerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clockInOutSpot, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(previousEmployeeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextEmployeeButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(netSalesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(netSalesField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(32, 32, 32)
                                .addComponent(employeeNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(returnManagerButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(clockInOutSpot, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(previousEmployeeButton)
                    .addComponent(nextEmployeeButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(netSalesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(netSalesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(returnManagerButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void previousEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousEmployeeButtonActionPerformed
        if(index>0){
            index--;
            employeeNameLabel.setText(posBackEnd.getEmployeeNameBackEnd(index));
            timeSheetTextArea.setText(posBackEnd.getEmployeeClockBackEnd(index));

        }
    }//GEN-LAST:event_previousEmployeeButtonActionPerformed

    private void nextEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextEmployeeButtonActionPerformed
        if(index<6){
            index++;
            employeeNameLabel.setText(posBackEnd.getEmployeeNameBackEnd(index));
            timeSheetTextArea.setText(posBackEnd.getEmployeeClockBackEnd(index));

        }

    }//GEN-LAST:event_nextEmployeeButtonActionPerformed

    private void netSalesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netSalesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netSalesFieldActionPerformed

    private void employeeNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeNameLabelActionPerformed

    }//GEN-LAST:event_employeeNameLabelActionPerformed

    private void returnManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnManagerButtonActionPerformed
       mainFrame.managerPanelReturn();
    }//GEN-LAST:event_returnManagerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane clockInOutSpot;
    private javax.swing.JTextField employeeNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField netSalesField;
    private javax.swing.JLabel netSalesLabel;
    private javax.swing.JButton nextEmployeeButton;
    private javax.swing.JButton previousEmployeeButton;
    private javax.swing.JButton returnManagerButton;
    private javax.swing.JTextArea timeSheetTextArea;
    // End of variables declaration//GEN-END:variables
}
